title: "EASYBASS.MASTER"
description: "Контрабасы · мастерская · прокат · продажа · Москва"
baseurl: "/EasyBass.Master"
url: "https://ontoslive.github.io"
markdown: kramdown
permalink: pretty
exclude:
  - README.md
