title: ONTOS.DEEP
description: Глубокий регистр · возбуждение · форма · звук
baseurl: "/EasyBass.Master"
url: "https://ontoslive.github.io"
markdown: kramdown
permalink: pretty
exclude:
  - README.md
