title: ONTOS.BASS
description: Контрабас · Москва · выпуски о звуке, теле и времени
baseurl: "/EasyBass.Master"
url: "https://ontoslive.github.io"
markdown: kramdown
permalink: pretty
exclude:
  - README.md
